apiVersion: v1
kind: Service
metadata:
  name: icnserver-cluster
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: icnserver-cluster
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: icnserver-cluster
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: icnserver-cluster
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                  - icnserver-cluster
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: <REGISTRY>/navigator:latest
        imagePullPolicy: Always
        name: icnserver-cluster
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        readinessProbe:
          httpGet:
            path: /navigator
            port: 9080
            httpHeaders:
              - name: Content-Encoding
                value: gzip
          initialDelaySeconds: 10
          periodSeconds: 2
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/plugins"
            subPath: icn/plugins
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/viewerconfig/logs"
            subPath: icn/viewerlog
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/viewerconfig/cache"
            subPath: icn/viewercache
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/logs"
            subPath: icn/logs
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides"
            subPath: icn/configDropins/overrides
      volumes:
        - name: ecmcfgstore-pvc
          persistentVolumeClaim:
            claimName: ecmcfgstore
